### ISSUE TITLE
نسخه کرک شده

### ISSUE THREAD

**Issue by mohammadhosseinzavvar** [fakhravari/Stimulsoft-Reports.Web-for-.Net-Core-7#1]
سلام دوست عزیز
تشکر بابت آموزش و اقدامات خوبتون
این نسخه روی Core 7 تست شده ؟ کراش نمیکنه و بدون محدودیت هست ؟

**Comment by fakhravari** [comment]
با سلام
بله نسخه بدون خطا است، موارد زیر رعایت کنید

1) گزاشتن کد قسمت PostBuildEvent
2) استفاده از پوشه Packages در root و فایل سریال در Reports\license\license.key
3) بعد از پابلیش فولدر Packages را نیز یک بار بر روی dll ها replace کنید و در هاست بگزارید.
